import Footer from "@/components/Footer/footer";
import Navbar from "@/components/Navbar/Navbar";
import ShowComponent from "@/components/showComponent/showComponent";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { SearchProvider } from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <SearchProvider>
          <ShowComponent>
            <Navbar />
          </ShowComponent>
          {children}
          <Footer />
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
